# Generated by Django 4.2 on 2023-04-26 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0005_meep_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meep',
            new_name='Tweet',
        ),
    ]
